version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
    volumes: 
      - ./docker/postgres/volumes:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./docker/django-app/Dockerfile
    ports:
      - "1234:8000"
    environment:
      BANK_MODE: docker-prod
    depends_on:
      - db